# Generated by Django 3.2.4 on 2021-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount'),
        ),
    ]
